Traceback (most recent call last):
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/nanaboateng/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
sys.path.insert(0, '../modules')

# Euler step functions
from steppers import euler_step

# Function to compute an error in L2 norm
from norms import l2_diff

# Function to compute d^2 / dx^2 with second-order 
# accurate centered scheme
from matrices import d2_mat_dirichlet

# Function for the RHS of the heat equation and
# exact solution of our example problem
from pde_module import rhs_heat_centered, exact_solution
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 8>[0;34m()[0m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01msteppers[39;00m [38;5;28;01mimport[39;00m euler_step
[1;32m      7[0m [38;5;66;03m# Function to compute an error in L2 norm[39;00m
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnorms[39;00m [38;5;28;01mimport[39;00m l2_diff
[1;32m     10[0m [38;5;66;03m# Function to compute d^2 / dx^2 with second-order [39;00m
[1;32m     11[0m [38;5;66;03m# accurate centered scheme[39;00m
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatrices[39;00m [38;5;28;01mimport[39;00m d2_mat_dirichlet

File [0;32m~/Documents/Book_Writing/Applied-Machine-Learning-with-Python/notebook/docs/04_PartialDifferentialEquations/../modules/norms.py:1[0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumba[39;00m [38;5;28;01mimport[39;00m njit
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mpy_l2_diff[39m(f1, f2):

File [0;32m~/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/numba/__init__.py:200[0m, in [0;36m<module>[0;34m[0m
[1;32m    197[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mFalse[39;00m
[1;32m    199[0m _ensure_llvm()
[0;32m--> 200[0m [43m_ensure_critical_deps[49m[43m([49m[43m)[49m
[1;32m    202[0m [38;5;66;03m# we know llvmlite is working as the above tests passed, import it now as SVML[39;00m
[1;32m    203[0m [38;5;66;03m# needs to mutate runtime options (sets the `-vector-library`).[39;00m
[1;32m    204[0m [38;5;28;01mimport[39;00m [38;5;21;01mllvmlite[39;00m

File [0;32m~/opt/anaconda3/envs/solving_pde_mooc/lib/python3.10/site-packages/numba/__init__.py:140[0m, in [0;36m_ensure_critical_deps[0;34m()[0m
[1;32m    138[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mNumba needs NumPy 1.18 or greater[39m[38;5;124m"[39m)
[1;32m    139[0m [38;5;28;01melif[39;00m numpy_version [38;5;241m>[39m ([38;5;241m1[39m, [38;5;241m21[39m):
[0;32m--> 140[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mNumba needs NumPy 1.21 or less[39m[38;5;124m"[39m)
[1;32m    142[0m [38;5;28;01mtry[39;00m:
[1;32m    143[0m     [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m

[0;31mImportError[0m: Numba needs NumPy 1.21 or less
ImportError: Numba needs NumPy 1.21 or less

